#!/bin/bash
#
## 
## Usage: ./nyphil <document-id> <#-pages-to-download> <resolution> 
##
## <document-id>:		Four digit number. Ex. 1786.
## <#-pages-to-download>:	number of pages to download. Ex. 20.
## <resolution>:		1200, 2000, or 3000
##
set -e
prog="$0"
docid="$1"
numpg="$2"
res="$3"
me=`basename "$prog"`

dohelp () {
  grep '^##' "$prog" | sed -e 's/^##//' -e "s/_PROG_/$me/" 1>&2
}

if [[ -z $docid ]]; then
	dohelp
	exit
elif [[ -z $numpg ]]; then
	dohelp
	exit
elif [[ -z $res ]]; then
	res=3000
fi

mkdir -p $docid
pushd $docid
for num in $(seq -w 001 $numpg); do
	wget -O "$num".jpg "http://archives.nyphil.org/index.php/jp2/|MS|1|"$docid"|MS_"$docid"_"$num".jp2/portrait/"$res
done
popd

echo All done

exit
